switch back to gcloud alpha because of error (#3)
I tried to switch to using `gcloud beta deploy` commands but I got the following error in Cloud Build during the container build:

```
Step #1: ERROR: (gcloud.beta.deploy.releases.create) INVALID_ARGUMENT: resource ids are must be lower-case letters, numbers, and hyphens, with the first character a letter, the last a letter or a number, and a 63 character maximum
Finished Step #1
ERROR
ERROR: build step 1 "google/cloud-sdk:latest" failed: step exited with non-zero status: 1
```

I'm just going to switch back to alpha and we can troubleshoot this later.